// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl-gBhYIIRiU5cFRvJj5SlUACWViZEUyM',
    appId: '1:665586155401:web:2e5e820c7642bd9f87eb58',
    messagingSenderId: '665586155401',
    projectId: 'instaclone-a18c3',
    authDomain: 'instaclone-a18c3.firebaseapp.com',
    storageBucket: 'instaclone-a18c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxSIsLntydTWVQpKq4BnhbiLIySr41SY',
    appId: '1:665586155401:android:8ec7723d8a933d2b87eb58',
    messagingSenderId: '665586155401',
    projectId: 'instaclone-a18c3',
    storageBucket: 'instaclone-a18c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNY429MN9GNsPa2gky6sC4q39x4TLrJW0',
    appId: '1:665586155401:ios:af0effd397eb886987eb58',
    messagingSenderId: '665586155401',
    projectId: 'instaclone-a18c3',
    storageBucket: 'instaclone-a18c3.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNY429MN9GNsPa2gky6sC4q39x4TLrJW0',
    appId: '1:665586155401:ios:af0effd397eb886987eb58',
    messagingSenderId: '665586155401',
    projectId: 'instaclone-a18c3',
    storageBucket: 'instaclone-a18c3.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl-gBhYIIRiU5cFRvJj5SlUACWViZEUyM',
    appId: '1:665586155401:web:4bbc7c168e8a8b6187eb58',
    messagingSenderId: '665586155401',
    projectId: 'instaclone-a18c3',
    authDomain: 'instaclone-a18c3.firebaseapp.com',
    storageBucket: 'instaclone-a18c3.appspot.com',
  );
}
